version: "3.7"

services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=jawstutorial
    ports:
      - 5432:5432