# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres_pod
spec:
  containers:
  - args:
    - postgres
    image: docker.io/library/postgres:14-alpine
    name: postgres
    ports:
    - containerPort: 5432
      hostPort: 5432
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: 123
    - name: POSTGRES_DB
      value: jawstutorial
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 03672f8cae398d1588dbd7d3ef6c436736a5480d8dcb3802cb015cb05c9dfb88-pvc
  volumes:
  - name: 03672f8cae398d1588dbd7d3ef6c436736a5480d8dcb3802cb015cb05c9dfb88-pvc
    persistentVolumeClaim:
      claimName: 03672f8cae398d1588dbd7d3ef6c436736a5480d8dcb3802cb015cb05c9dfb88

