package com.bezkoder.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// dynamic table name, see: https://blog.jayway.com/2013/10/09/dynamic-table-name-in-dynamodb-with-java-dynamomapper/
@DynamoDBTable(tableName = "REPLACED_BY_VALUE_IN_ENV_VAR_DYNAMODB_TABLE")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class TutorialDynamoDB {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String title;

	@DynamoDBAttribute
	private String description;

	@DynamoDBAttribute
	private boolean published;

	public TutorialDynamoDB(String title, String description, boolean published) {
		this.title = title;
		this.description = description;
		this.published = published;
	}

	@Override
	public String toString() {
		return "Tutorial [id=" + id + ", title=" + title + ", desc=" + description + ", published=" + published + "]";
	}

}
